# Generated by Django 3.2.16 on 2023-04-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='TITLE')),
                ('description', models.TextField(blank=True, verbose_name='DESCRIPTION (or EMPTY)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='STHUMBNAIL (or EMPTY)')),
                ('upload', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='FILE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CREATED DATE')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='UPDATED DATE')),
            ],
        ),
    ]
