# Generated by Django 3.2.16 on 2023-04-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='FILE'),
        ),
    ]
