# Generated by Django 3.2.16 on 2023-02-28 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='TITLE')),
                ('text', models.TextField(verbose_name='TEXT')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE')),
            ],
        ),
    ]
