# Generated by Django 3.2.16 on 2023-03-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employ',
        ),
    ]
