# Generated by Django 3.2.16 on 2023-03-12 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0002_rename_employee_employ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33, verbose_name='club name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
        ),
        migrations.AddField(
            model_name='employ',
            name='club',
            field=models.ManyToManyField(to='employ.Club', verbose_name='club'),
        ),
    ]
