# Generated by Django 3.2.16 on 2022-11-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20221129_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='ANONYMOUS', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(default='AROUSAL'),
        ),
    ]
