# Generated by Django 3.2.16 on 2022-11-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20221129_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='company',
            field=models.CharField(choices=[('bbc', 'BBC'), ('cnn', 'CNN'), ('dw', 'DW'), ('nhk', 'NHK')], default='DW', max_length=20),
        ),
    ]
