# Generated by Django 4.1.5 on 2023-01-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='snsGood',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='snsRead',
            field=models.IntegerField(),
        ),
    ]
